### ISSUE TITLE
The MessageHandler should not return `null` but throw a `DBusException`

### ISSUE THREAD

**Issue by swiesend** [purejava/kdewallet#1]
My new `MessageHandler` avoids returning `null` on my `2.0.0` branch as this only leads to problems, if the case is not handled properly.

https://github.com/purejava/kdewallet/blob/acd9595106a958b08fec97b2cc01cc771f445468/src/main/java/org/freedesktop/dbus/handlers/MessageHandler.java#L30-L55

**see:** https://github.com/swiesend/secret-service/blob/c7399ea1f2d6031158a64a0459a066a35c7f9cbf/src/main/java/org/freedesktop/secret/handlers/MessageHandler.java#L34-L75

**see also:** https://github.com/swiesend/secret-service/issues/6

**Comment by purejava** [comment]
Thanks for pointing me to the upcoming new release with the improved `MessageHandler`. It‘s good to have a `DBusException` instead of returning `null` in case of `MessageHandler` having problems sending a message via D-Bus. This will add good robustness to the library for cases where the whole D-Bus back-end fails.
I‘ll adopt your changes when they are released.

Anyway, kdewallet does not have the same challenges secret-service has concerning the handling of `org.freedesktop.Secret.Errors` within `MessageHandler`, as they just do not exist in the wallet / KDE context.

Cheers!
